export const PROJECTS = [
  {
    id: 1,
    title: "Jordan Mitchell Coach",
    image: "/Landing-Page.png",
    tags: ["Landing Page", "Booking Flow", "Mobile-First"],
    cat: "Landing Page",
    live: "https://coach-landingpage.vercel.app/",
    github: "https://github.com/Mudasra/Coach-LandingPage",
    gradient: "from-cyan-500/20 to-blue-600/20",
  },
   {
    id: 2,
    title: "DevTinder",
    image: "/DevTinder.png",
    tags: ["React", "Developer Matching", "Swipe UI"],
    cat: "Web App",
    live: "https://dev-tinder-one-sigma.vercel.app/",
    github: "https://github.com/Mudasra/DevTinder",
    gradient: "from-violet-500/20 to-purple-700/20",
  },
{
    id: 3,
    title: "ClarityCoach Funnel",
    image: "/Coach-Funnel.png",
    tags: ["Lead Funnel", "Opt-in Page", "Book a Call"],
    cat: "Coach Funnel",
    live: "https://career-clarity-conversion-funnel.vercel.app/",
    github: "https://github.com/Mudasra/career-clarity-conversion-funnel",
    gradient: "from-violet-500/20 to-purple-700/20",
  },
];